apiVersion: v1
kind: Service
metadata:
  labels:
   app: oapui-service
  name: oapui-service
  namespace: ns-monitor
spec:
  ports:
  - port: 8080
    name: http-8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sky-oap-ui
